(function(){"use strict";if(window.__clGlobalSearch)return;window.__clGlobalSearch=true;
const norm=s=>(s||"").toString().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
const esc=s=>(s||"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let products=[];
function shell(){
 document.body.insertAdjacentHTML("beforeend",`<div class="cl-command" hidden><section class="cl-command__panel" role="dialog" aria-modal="true" aria-labelledby="cl-search-title"><div class="cl-command__top"><div class="cl-command__brand"><span class="cl-command__mark"><img src="/images/Logo Colegiolibre horizontal.png" alt="ColegioLibre"></span><span><strong id="cl-search-title">Buscar en ColegioLibre</strong><small>Encontrá materiales, libros, útiles y colegios</small></span></div><button class="cl-command__close" type="button" aria-label="Cerrar búsqueda">×</button></div><div class="cl-command__search"><span class="cl-command__glass">⌕</span><input type="search" placeholder="¿Qué estás buscando?" autocomplete="off" spellcheck="false"><kbd>ESC</kbd></div><div class="cl-command__results"></div><footer class="cl-command__footer"><span><kbd>↑</kbd><kbd>↓</kbd> para explorar · <kbd>↵</kbd> para buscar</span><a href="/explorar">Ver búsqueda avanzada</a></footer></section></div>`);
 const modal=document.querySelector(".cl-command"),input=modal.querySelector("input"),results=modal.querySelector(".cl-command__results");
 const open=async()=>{modal.hidden=false;document.documentElement.classList.add("cl-search-open");requestAnimationFrame(()=>input.focus());if(!products.length&&window.cargarProductosDesdeSupabase)products=await window.cargarProductosDesdeSupabase();render(input.value)};
 const close=()=>{modal.hidden=true;document.documentElement.classList.remove("cl-search-open")};
 modal.querySelector(".cl-command__close").onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
 document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();modal.hidden?open():close()}if(e.key==="Escape"&&!modal.hidden)close()});
 input.oninput=()=>render(input.value);input.addEventListener("keydown",e=>{if(e.key==="Enter"&&input.value.trim())location.href="/explorar?q="+encodeURIComponent(input.value.trim())});
 function render(q){const query=norm(q);if(!query){results.innerHTML=`<div class="cl-command__section-title">Accesos rápidos</div><div class="cl-command__quick"><a href="/explorar"><span class="cl-command__icon">⌕</span><span><strong>Explorar</strong><small>Descubrí publicaciones</small></span><b>→</b></a><a href="/apuntes"><span class="cl-command__icon">A</span><span><strong>Apuntes</strong><small>Resúmenes y exámenes</small></span><b>→</b></a><a href="/?sort=newest"><span class="cl-command__icon">↗</span><span><strong>Recién publicados</strong><small>Lo último de la comunidad</small></span><b>→</b></a></div><div class="cl-command__hint">Empezá a escribir para buscar en todo ColegioLibre.</div>`;return}
 if(!products.length){results.innerHTML=`<a class="cl-command__item cl-command__search-all" href="/explorar?q=${encodeURIComponent(q)}"><span class="cl-command__icon">⌕</span><span><strong>Buscar “${esc(q)}”</strong><small>Ver todos los resultados</small></span><b>→</b></a>`;return}
 const hits=products.filter(p=>norm([p.title,p.description,p.category,p.school_name,p.location,p.seller_name,p.subject,p.level,p.year].join(" ")).includes(query)).slice(0,6);
 results.innerHTML=hits.length?`<div class="cl-command__section-title">Resultados</div>`+hits.map(p=>`<a class="cl-command__item" href="/producto?id=${encodeURIComponent(p.id)}"><img src="${esc(p.image_url||"images/materiales.webp")}" alt=""><span><strong>${esc(p.title)}</strong><small>${esc(p.category||"Material")} · ${esc(p.school_name||p.location||"ColegioLibre")}</small></span><b>${Number(p.price||0).toLocaleString("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0})}</b></a>`).join("")+`<a class="cl-command__more" href="/explorar?q=${encodeURIComponent(q)}">Ver todos los resultados para “${esc(q)}” <span>→</span></a>`:`<div class="cl-command__empty"><span class="cl-command__empty-icon">⌕</span><strong>No encontramos “${esc(q)}”</strong><small>Probá con otras palabras o buscá por materia, colegio o categoría.</small><a href="/explorar?q=${encodeURIComponent(q)}">Abrir búsqueda avanzada</a></div>`}
 }
 document.readyState==="loading"?document.addEventListener("DOMContentLoaded",shell):shell();
})();
