-- ColegioLibre · monitoreo técnico gratuito y respetuoso de privacidad

create table if not exists public.client_errors (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  page_path text not null,
  error_source text,
  error_message text not null,
  line_number integer,
  column_number integer,
  app_version text,
  created_at timestamptz not null default now()
);

create index if not exists client_errors_created_at_idx
  on public.client_errors (created_at desc);

create index if not exists client_errors_user_id_idx
  on public.client_errors (user_id, created_at desc);

alter table public.client_errors enable row level security;

drop policy if exists "Users can report own client errors"
  on public.client_errors;
create policy "Users can report own client errors"
  on public.client_errors
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Admins can read client errors"
  on public.client_errors;
create policy "Admins can read client errors"
  on public.client_errors
  for select
  to authenticated
  using (public.is_admin_account(auth.uid()));

revoke all on public.client_errors from anon;
grant insert on public.client_errors to authenticated;
grant select on public.client_errors to authenticated;

-- Retención recomendada: ejecutar periódicamente desde una tarea programada.
-- delete from public.client_errors where created_at < now() - interval '30 days';
